= README - INFORMACJE

:githubdir: https://github.com/rperkow
:projectdir: /_INFO_
:project01dir: /InternetRzeczy
:project02dir: /RankDatabase
:project03dir: /RankApplication
:project04dir: /KursyPWN
:blobmasterdir: /blob/master

## Wstęp

Poniżej znajduje się skrócony opis programu ukończonego kursu PWN (Back-End Developer).

Kurs odbył się w dniach: 2017.11.06-2017.12.19 (6 tygodni).

## Program kursu

Swoim zakresem objął następujące tematy:

. MySQL - system zarządzania relacyjnymi bazami danych (MySQL Community Server, MySQL Workbench).
. Git – rozproszony system kontroli wersji (Git Bash, GitHub, TortoiseGit).
. Python - obiektowy język programowania (Wing Python, Eclipse PyDev).
. Wybrane techniki Front-End (HTML, CSS, Bootstrap, jQuery).
. Java - obiektowy język programowania (Eclipse IDE, JavaSE, JDBC, JavaFX).
. DPP - Dobre Praktyki Programowania (UpperCase, lowercase, camelCase, notacja węgierska).
. Spring - szkielet tworzenia aplikacji (Maven, Tomcat, Spring Tool Suite).

## Projekty zrealizowane

* {githubdir}{project01dir}{blobmasterdir}/README.adoc[Projekt nr 1]: Prosta strona domowa (HTML, CSS)
* {githubdir}{project02dir}{blobmasterdir}//RankDatabase/README.adoc[Projekt nr 2]: Implementacja relacyjnej bazy danych (MySQL)
* {githubdir}{project03dir}{blobmasterdir}/RankApplication/README.adoc[Projekt nr 3]: Aplikacja w języku Python łącząca z bazą danych (Python, PyMySQL)
* {githubdir}{project04dir}{blobmasterdir}/KursyPWN/README.adoc[Projekt nr 4]: Program do oceny projektów kursantów (JavaSE, JDBC, JavaFX, MySQL)

## Projekty w realizacji

* [Projekt nr 5]: Wykorzystanie szkieletu Spring do tworzenia aplikacji (JavaEE, Spring, JSP, XML)

## Projekty planowane

* [Projekt nr 6]: Przykładowa gra strategiczna (Java)
